###
#审核通过
POST http://localhost:8102/admin/reviewReg?_id=5bd232083931128db02d9848 HTTP/1.1
#POST http://oa.chinahuian.cn/platform/admin/corp/reviewReg?_id=5a9675d74446e17f1df0d447 HTTP/1.1
content-type: application/json
Accept: application/json

{
  "status": "0"
}