#企业注册1
POST http://localhost:8102/api/register/create HTTP/1.1
#POST http://oa.chinahuian.cn/platform/corp/register/create HTTP/1.1
content-type: application/json
Accept: application/json

{
  "corpname": "慧安通信",
  "email": "hatx@qq.cn",
  "password": "123456"
}

###
#企业注册2
#POST http://localhost:7001/register/complete?_id=5a95c5599ceec810809c92d5 HTTP/1.1
POST http://localhost:8102/api/register/complete?id=5bd65b90e7f133acd823a07d HTTP/1.1
#POST http://oa.chinahuian.cn/platform/corp/register/complete?_id=5a9675d74446e17f1df0d447 HTTP/1.1
content-type: application/json
Accept: application/json

{
  "description": "none",
  "info": {
    "corpcode": "1234567890",
    "corptype": "0",
    "scale": {
      "code": "100",
      "name": "少于50人"
    },
    "nature": {
      "code": "150002",
      "name": "民营企业"
    }, 
    "industry": {
      "code": "34",
      "name": "软件和信息技术服务业"
    }, 
    "city": {
      "code": "220100",
      "name": "吉林省长春市"
    }, 
    "legalPerson": "刘玉国",
    "registerTime": "2018-02-28",
    "registerMoney": "100万"
  },
  "contact": {
    "person": "刘玉国",
    "mobile": "13500000001",
    "phone": "13500000001",
    "email": "10000@qq.com",
    "url": "http://www.baidu.com",
    "postcode": "130000",
    "address": "吉林省长春市"
  },
  "credentials": {
    "yyzz": "营业执照.jpg",
    "zzjgdmz": "组织机构代码证.jpg",
    "swdjz": "税务登记证.jpg",
    "sbjntz": "社保缴纳通知.jpg"
  }
}

###
#检查企业代码是否存在
POST http://localhost:7001/api/register/check HTTP/1.1
#POST http://oa.chinahuian.cn/platform/corp/register/check HTTP/1.1
content-type: application/json
Accept: application/json

{
    "corpcode": "1234567890"
}

###
#检查企业代码是否存在
POST http://localhost:7001/api/register/check HTTP/1.1
#POST http://oa.chinahuian.cn/platform/corp/register/check HTTP/1.1
content-type: application/json
Accept: application/json

{
    "corpname": "福瑞科技1"
}
